# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-30 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'progress', 'verbose_name_plural': 'progress'},
        ),
        migrations.AlterField(
            model_name='progress',
            name='content',
            field=models.TextField(verbose_name='progress content'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='project'),
        ),
    ]
