# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-22 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pub_time'], 'permissions': (('add_news', 'Can add news'), ('delete_news', 'can delete news'), ('edit_news', 'can modify news')), 'verbose_name': '\u65b0\u95fb'},
        ),
    ]
