# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-22 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20161122_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pub_time'], 'verbose_name': '\u65b0\u95fb'},
        ),
    ]
