# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-26 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('teamName', models.CharField(max_length=20)),
                ('priority', models.IntegerField()),
                ('profile', models.TextField()),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
