# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-22 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='member',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='teamName',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
