# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-22 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article_publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('href', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=20)),
                ('pub_time', models.DateField()),
            ],
        ),
    ]
