# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-27 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20161127_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_publish',
            name='href',
            field=models.CharField(max_length=2000),
        ),
    ]
