# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-30 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20161127_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_publish',
            options={'verbose_name': 'article by team members', 'verbose_name_plural': 'articles by team members'},
        ),
        migrations.AlterField(
            model_name='article_publish',
            name='author',
            field=models.CharField(max_length=200, verbose_name='article authors'),
        ),
        migrations.AlterField(
            model_name='article_publish',
            name='href',
            field=models.CharField(max_length=2000, verbose_name='article link'),
        ),
        migrations.AlterField(
            model_name='article_publish',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='project belong to'),
        ),
        migrations.AlterField(
            model_name='article_publish',
            name='pub_time',
            field=models.DateField(verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='article_publish',
            name='title',
            field=models.CharField(max_length=200, verbose_name='article title'),
        ),
    ]
