# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-30 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-date'], 'verbose_name': 'meeting', 'verbose_name_plural': 'meetings'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='content',
            field=models.TextField(verbose_name='meeting content'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(verbose_name='meeting time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=100, verbose_name='meeting name'),
        ),
    ]
