# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-27 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-pub_time'], 'verbose_name': '\u901a\u77e5', 'verbose_name_plural': '\u901a\u77e5'},
        ),
    ]
