# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-26 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('category', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('basicInformation', models.TextField()),
                ('article_outside', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
