# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-27 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('category', models.CharField(choices=[('\u56e2\u961f\u6570\u636e\u5171\u4eab', 'team'), ('\u7ad9\u5916\u6570\u636e\u5e93', 'outside'), ('\u5e38\u7528\u5206\u6790\u5de5\u5177', 'usual')], max_length=20, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
