# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-30 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('\u56e2\u961f\u6570\u636e\u5171\u4eab', 'team'), ('\u7ad9\u5916\u6570\u636e\u5e93', 'outside'), ('\u5e38\u7528\u6570\u636e\u5de5\u5177', 'usual')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
